# Generated by Django 6.0.1 on 2026-02-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_group_message_groupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher'), ('moderator', 'Moderator'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
