# Generated by Django 6.0.1 on 2026-02-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_groupmember_teacher_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
    ]
