# Generated by Django 6.0.1 on 2026-02-27 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0007_groupmember_is_muted'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('account_create', 'Account Created'), ('account_delete', 'Account Deleted'), ('account_update', 'Account Updated'), ('message_send', 'Message Sent'), ('message_delete', 'Message Deleted'), ('group_create', 'Group Created'), ('group_delete', 'Group Deleted'), ('group_update', 'Group Updated'), ('member_join', 'Member Joined'), ('member_leave', 'Member Left'), ('member_remove', 'Member Removed'), ('role_change', 'Role Changed')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='auth_system.group')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='auth_system_timesta_28ddc4_idx'), models.Index(fields=['user', '-timestamp'], name='auth_system_user_id_317509_idx')],
            },
        ),
    ]
