# Generated by Django 6.0.1 on 2026-03-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='class_number',
            field=models.PositiveIntegerField(blank=True, help_text='Student number in class (unique per group)', null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='grade',
            field=models.CharField(blank=True, help_text='Student grade (e.g., 10, 11, 12)', max_length=10, null=True),
        ),
    ]
