# Generated by Django 6.0.1 on 2026-03-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0009_groupmember_class_number_groupmember_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_grade',
            field=models.CharField(blank=True, choices=[('12A', 'Grade 12A'), ('12B', 'Grade 12B')], default='12A', max_length=10, null=True),
        ),
    ]
