# Generated by Django 6.0.1 on 2026-03-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0010_customuser_preferred_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_class_group',
            field=models.BooleanField(default=False, help_text='Hidden group for managing class numbering'),
        ),
    ]
