# Generated by Django 6.0.1 on 2026-03-21 13:54

from django.db import migrations


def populate_grades(apps, schema_editor):
    """Populate grade field for existing student members from their user's preferred_grade"""
    GroupMember = apps.get_model('auth_system', 'GroupMember')
    CustomUser = apps.get_model('auth_system', 'CustomUser')
    
    # Get all student members without a grade
    student_members = GroupMember.objects.filter(role='student', grade__isnull=True)
    
    for member in student_members:
        # Get the user's preferred grade
        member.grade = member.user.preferred_grade or '12A'
        member.save(update_fields=['grade'])


def reverse_grades(apps, schema_editor):
    """Reverse: set grades back to null"""
    GroupMember = apps.get_model('auth_system', 'GroupMember')
    GroupMember.objects.filter(role='student').update(grade=None)


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0011_group_is_class_group'),
    ]

    operations = [
        migrations.RunPython(populate_grades, reverse_grades),
    ]
